name: Lint

on:
  push:
    branches: [ main ]
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'wxt.config.ts'
      - 'eslint.config.mjs'
      - '**/*.ts'
  pull_request:
    branches: [ main ]
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'wxt.config.ts'
      - 'eslint.config.mjs'
      - '**/*.ts'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run lint
