# Upon release, build Chrome and Firefox packages and upload both zips to the Release
name: Create Extension Zip

on:
  release:
    types:
      - created

jobs:
  create-and-upload-zip:
    name: Create and Upload ZIP
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build Chrome and Firefox packages
        run: npm run build

      - name: Create Chrome ZIP
        run: cd dist/chrome && zip -r ../../test-cards-chrome.zip .

      - name: Create Firefox ZIP
        run: cd dist/firefox && zip -r ../../test-cards-firefox.zip .

      - name: Upload release binaries
        run: gh release upload ${{ github.event.release.tag_name }} ./test-cards-chrome.zip ./test-cards-firefox.zip
        env:
          GH_TOKEN: ${{ github.token }}
